name: Action CI
on: [push]

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.1.1
      - name: Run my own container action
        uses: ./
        with:
          who-to-greet: '@wulfland'
